---

# https://eslint.org/docs/user-guide/configuring#specifying-environments
plugins:
  - jest
  - babel

env:
  node: true
  jest: true

rules:
  no-console: 0

# https://github.com/babel/babel-eslint
parser: babel-eslint


extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
